### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wanda-carlson**

### CODE REVIEW

**Review by henry-richard — CHANGES_REQUESTED** [review]
message1

**Review by henry-richard — CHANGES_REQUESTED** [review]
message2

**Review by henry-richard — CHANGES_REQUESTED** [review]
message3

**Review by wanda-carlson — COMMENTED** [review]
thanks, i'll "update" it.

**Review by henry-richard — APPROVED** [review]

**Review by henry-richard — APPROVED** [review]

**Review by henry-richard — APPROVED** [review]

**Pull request closed without merging**
