### PR TITLE
AI bot commands test.md

### PR DESCRIPTION
**Pull request by henry-richard**

### CODE REVIEW

**Comment by henry-richard** [comment]
**[@Pullflow{pre}](https://pre.pullflow.app)** request review from @wanda-carlson

**Comment by henry-richard** [comment]
**[@Pullflow{pre}](https://pre.pullflow.app)** assign to @wanda-carlson

**Comment by henry-richard** [comment]
**[@Pullflow{pre}](https://pre.pullflow.app)** add labels label1,label2

**Review by wanda-carlson — CHANGES_REQUESTED** [review]
Change it please

**Pull request merged**
