### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wanda-carlson**

### CODE REVIEW

**Review by henry-richard — CHANGES_REQUESTED** [review]
“Feel free to merge …. “

**Review by henry-richard — CHANGES_REQUESTED** [review]
“Feel free to merge …. “

**Review by henry-richard — CHANGES_REQUESTED** [review]
“Feel free to merge ….“

**Review by henry-richard — CHANGES_REQUESTED** [review]
Hassan

**Comment by wanda-carlson** [comment]
<p> Hi this is html tag </p>

**Comment by wanda-carlson** [comment]
<p> This is html tag </p>

**Comment by henry-richard** [comment]
<p>This is html tag </p>

**Comment by henry-richard** [comment]
<p>This is html tag </p>

**Comment by henry-richard** [comment]
hi

**Comment by wanda-carlson** [comment]
hi

**Review by henry-richard — COMMENTED** [review]
&lt;p&gt; Hi this is html &lt;/p&gt;

**Pull request closed without merging**
