### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wanda-carlson**
</p>
<p>  </p>
<h2 id="implementation"> Implementation </h2>
<p> Call for the editing holidays action <code> action_bulk_update_holidays </code> using a worker when the changes are affecting more than 100 people. <p>
<p> Any changes to the holiday group will be seen immediately (e.g. name, adding/deleting/editing of holidays), it's just the time offs in the planners and person dashboards that may take a while to update. </p>

### CODE REVIEW

**Review by henry-richard — CHANGES_REQUESTED** [review]
Hi

**Review by chad-daniels — CHANGES_REQUESTED** [review]
"Hi"Hi

**Review by chad-daniels — CHANGES_REQUESTED** [review]
Hi

**Review by chad-daniels — CHANGES_REQUESTED** [review]
Hi

**Review by henry-richard — CHANGES_REQUESTED** [review]
hi change

**Review by henry-richard — CHANGES_REQUESTED** [review]
Hi change

**Review by henry-richard — CHANGES_REQUESTED** [review]
changes

**Review by henry-richard — CHANGES_REQUESTED** [review]
changes

**Review by henry-richard — CHANGES_REQUESTED** [review]
ch

**Review by henry-richard — APPROVED** [review]
approve

**Review by henry-richard — APPROVED** [review]
Feel free to merge this

**Review by henry-richard — APPROVED** [review]
app

**Review by henry-richard — APPROVED** [review]
approved

**Review by henry-richard — COMMENTED** [review]
add review comment

**Review by henry-richard — COMMENTED** [review]
comment

**Review by henry-richard — COMMENTED** [review]
comment

**Review by henry-richard — COMMENTED** [review]
cm

**Review by henry-richard — COMMENTED** [review]
add review comment

**Pull request closed without merging**
