### PR TITLE
notifications 0.6

### PR DESCRIPTION
**Pull request by wanda-carlson**
notifications 0.6!

- [ ] Fix check lists
- [x] Fix check runs 
- [x] Fix pr updates
- [ ] Fix tests
- [ ] Fix review comments

### CODE REVIEW

**Comment by wanda-carlson** [comment]
Re-opened pull request 99: notifications 0.6!

**Review by henry-richard — CHANGES_REQUESTED** [review]
Don't like it

**Review by henry-richard — DISMISSED** [review]
some more changes

**Review by henry-richard — CHANGES_REQUESTED** [review]
Hello

**Review by henry-richard — CHANGES_REQUESTED** [review]
Change stuff

**Pull request closed without merging**
