### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by henry-richard**

### CODE REVIEW

**Comment by henry-richard** [comment]
**testing**

**Review by wanda-carlson — COMMENTED** [review]
**testing 2**

**Comment by henry-richard** [comment]
**Slack user** cm "**this is bold**"

**Review by henry-richard — COMMENTED** [review]
*this is bold*

**Review by henry-richard — COMMENTED** [review]
*message*

**Review by henry-richard — COMMENTED** [review]
*testing bold*

**Pull request closed without merging**
