### PR TITLE
Create hello_world.py

### PR DESCRIPTION
**Pull request by wanda-carlson**
Testing

### CODE REVIEW

**Comment by wanda-carlson** [comment]
Testing to check comments

**Comment by wanda-carlson** [comment]
**Henry Richard**

**Comment by wanda-carlson** [comment]
Hi @wanda-carlson

**Comment by henry-richard** [comment]
Hi @wanda-carlson

**Comment by bert-griffin** [comment]
hi there

**Comment by bert-griffinn** [comment]
hello

**Comment by bert-griffinn** [comment]
no thanks

**Comment by bert-griffinn** [comment]
hello there

**Comment by bert-griffin** [comment]
yoyo

**Review by henry-richard — APPROVED** [review]

**Pull request merged**
