### PR TITLE
v0.8.0 Reopening PR

### PR DESCRIPTION
**Pull request by wanda-carlson**
Testing for Image unfurling and reopening of PR.

Screen Shot 2022-01-06 at 2 57 26 PM

### CODE REVIEW

**Comment by wanda-carlson** [comment]
@henry-richard can you have a look?

**Comment by henry-richard** [comment]
@wanda-carlson Im going to close it for now

**Comment by henry-richard** [comment]
I have revoked pullflow on my slack

**Comment by wanda-carlson** [comment]
This is ok @wanda-carlson

**Comment by henry-richard** [comment]
Is this ok @wanda-carlson?

**Comment by wanda-carlson** [comment]
Yes its fine

**Comment by henry-richard** [comment]
This should go to GitHub

**Pull request closed without merging**
