### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wanda-carlson**
June 16, 2022.

### CODE REVIEW

**Comment by wanda-carlson** [comment]
@Pullflow assign **Henry Richard**

**Comment by chad-daniels** [comment]
@Pullflow assign @wanda-carlson

**Review by wanda-carlson — COMMENTED** [review]
Can you check this <@U028E1LHYAF>

**Review by wanda-carlson — COMMENTED** [review]
Can you check this <@U028E1LHYAF>

**Review by wanda-carlson — COMMENTED** [review]
Thanks, I'll "update" it.

**Review by wanda-carlson — COMMENTED** [review]
Can you check this <@U028E1LHYAF>

**Review by chad-daniels — CHANGES_REQUESTED** [review]
minor changes please

**Review by chad-daniels — APPROVED** [review]

**Pull request merged**
