### PR TITLE
Update hello.py

### PR DESCRIPTION
**Pull request by wanda-carlson**
New PR

### CODE REVIEW

**Comment by henry-richard** [comment]
s1

**Comment by henry-richard** [comment]
s2

**Comment by henry-richard** [comment]
s3

**Comment by wanda-carlson** [comment]
l1

**Comment by wanda-carlson** [comment]
l3

**Comment by wanda-carlson** [comment]
l2

**Comment by wanda-carlson** [comment]
k1

**Comment by wanda-carlson** [comment]
k2

**Comment by wanda-carlson** [comment]
k3

**Pull request closed without merging**
